### ISSUE TITLE
Bug with home screen

### ISSUE THREAD

**Issue by Nodrex** [Nodrex/Testomania#196]
When leaving the app open on the home screen, it happens after a couple of minutes.
![image](https://user-images.githubusercontent.com/6556678/187075510-4208f5c9-98f5-4081-97bb-5182982ca860.png)
I want to mention that sometimes compose tries to recompose UI on device when we are changing it in studio, so maybe this bug is related to this case

**Comment by kdiakonidze** [comment]
does it always happens with connected device? has someone this kind observation?

**Comment by Nodrex** [comment]
Good question, no me and  @shalva97 we discovered it only once

**Comment by Nodrex** [comment]
I have not seen this while, so closing
