### ISSUE TITLE
OpenTDB Symbols problem

### ISSUE THREAD

**Issue by Nodrex** [Nodrex/Testomania#285]
We need to convert specific strings to real symbols, this problem is only for OpenTDB Api
![Inked318629853_562083215252501_5275786953734912817_n](https://user-images.githubusercontent.com/6556678/207704657-80acda3e-410f-4fd9-95ba-11f93fba2207.jpg)

**Comment by shalva97** [comment]
I think this can be fixed by Andorid's String.parseAsHTML or something similar named function
