### ISSUE TITLE
Self hosted stable diffusion

### ISSUE THREAD

**Issue by Nodrex** [Nodrex/Testomania#314]
We need to host some image generate software to generate illustrations for Testomania App
Also maybe if it will work we can even sell our image generator API

**Comment by Nodrex** [comment]
Maybe be useful:
https://www.linkedin.com/posts/christopherobereder_ai-data-jobs-activity-7022212750399430656-Zx6A?utm_source=share&utm_medium=member_desktop

**Comment by Nodrex** [comment]
https://www.howtogeek.com/853529/hardware-for-stable-diffusion/
https://adashop.ge/product/63b69a81ec8938e3f50778ec

**Comment by Nodrex** [comment]
Relates to this task also:
https://github.com/Nodrex/Testomania/issues/279

**Comment by shalva97** [comment]
https://adashop.ge/product/627e1662e5b4303c2c8c1f75

**Comment by Nodrex** [comment]
Maybe it will be helpful:
https://levelup.gitconnected.com/8-ways-chatgpt-helps-you-boost-your-programming-productivity-8f4999e3a624#:~:text=7%20%E2%80%94%20Generate%20training,and%20%E2%80%9Csports%E2%80%9D.
