### ISSUE TITLE
App License ?

### ISSUE THREAD

**Issue by wakaztahir** [Nodrex/Testomania#399]
Hi, I need to create an app for quizes, I was thinking about creating my own but then I found yours
I was looking for an app with these features
Create Quiz , Update Quiz and Users can Answer Quizes
Its a small app I need, I see that your app doesn't have the functionality I want but It has a starting point
I will remove About Section, I will create another Section with Current Quizez, like "System Quizes"
and another section "User Quizes"

The repo has no license. If you can give me permission to use your app as a starting point, I'll be thankful. I don't intend to make my source code open, Because most of the things I want to build are very important for me. I have already imported your repo and removed most of the code. I am pretty sure you won't be bothered but I still thought to confirm it.

**Comment by Nodrex** [comment]
https://github.com/Nodrex/Testomania/blob/main/LICENSE
